name: My First CI

# 1. เริ่มทำเมื่อไหร่?
on: [push]

jobs:
  # 2. ชื่อ Job (งานเหมา)
  check-code-quality:
    runs-on: ubuntu-latest
    
    # 3. ขั้นตอนย่อย
    steps:
      - name: Check out code (ดึงโค้ดล่าสุดมา)
        uses: actions/checkout@v4
      
      - name: Say Hello (ทักทาย)
        run: echo "กำลังเริ่มตรวจสอบโค้ดครับ..."